path: /content/drive/MyDrive/dataset  # 学習データセット（画像とアノテーションファイル）が入っているディレクトリのパスを自分のものに合わせてパスを書き直してください．
train: train/images  # 「path:」に書いたディレクトリの下にある画像が入っているディレクトリの相対パスを書いてください．
val: train/images  # 「train:」に書いたパスと同じものかまたはval用の画像が入ったディレクトリの相対パスを書いてください．
test:  # 何も書かなくていいです．

# Classes
nc: 1  # クラスの数．任意の数を入力してください．
names: ['class name']  # クラスの名前．なんでもいいです．